import { AiFillStar } from "react-icons/ai";

const data = [
  {
    img: "https://i.pinimg.com/originals/83/56/fd/8356fd183e98dd66e3ead810ec7e175e.jpg",
    title: "Orange plain shirt",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Only",
    color: "streetwear",
    category: "pearl",
    merch: "anime",
    skintone: "light",
    

  },
  {
    img: "https://i.pinimg.com/originals/93/23/51/932351f02b937774776cbcf67748ffd2.jpg",
    title: "White plain shirt",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Tokyo Talkies",
    color: "streatwear",
    category: "pearl",
    merch: "anime",
    skintone: "light",

  },

  {
    img: "https://i.pinimg.com/originals/56/19/c8/5619c83764f66bcbd7501f90c74c90e7.jpg",
    title: "Straight leg jeans",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Only",
    color: "streetwear",
    category: "pearl",
    merch: "anime",
    skintone: "light",

  },
  {
    img: "https://i.pinimg.com/originals/b6/29/8a/b6298a5efba7a1572b85b15b48dc8b46.jpg",
    title: "Denim shorts",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Levis",
    color: "streetwear",
    category: "pearl",
    merch: "anime",
    skintone: "light",

  },
  {
    img: "https://i.pinimg.com/originals/94/29/2e/94292eff6fa0768d7d3f9072d6416d52.jpg",
    title: "Formal style dress",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Only",
    color: "streatwear",
    category: "pearl",
    merch: "anime",
    skintone: "light",

  },
  {
    img: "https://i.pinimg.com/originals/3e/8b/a1/3e8ba1f8fc2295023a0bec1c530b24e7.png",
    title: "White strips leather jacket",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Adidas",
    color: "streatwear",
    category: "pearl",
    merch: "anime",
    skintone: "light",

  },

  {
    img: "https://i.pinimg.com/originals/e2/c8/20/e2c8203e4ffcc6f95b28c6332062396b.png",
    title: "Plain black jacket",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Adidas",
    color: "oldmoney",
    category: "inverted traingle",
    merch: "taylorswift",
    skintone: "light",

  },

  {
    img: "https://i.pinimg.com/originals/63/b1/13/63b1137e9b21611df19a3e6efff935e4.jpg",
    title: "Bombor jacket",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Adidas",
    color: "oldmoney",
    category: "inverted traingle",
    merch: "taylorswift",
    skintone: "light",
  
  },

  {
    img: "https://i.pinimg.com/originals/8b/6d/28/8b6d28e0080df4cb0b10b087a46c9dd5.png",
    title: "Y2k styled jacket",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Adidas",
    color: "oldmoney",
    category: "inverted traingle",
    merch: "taylorswift",
    skintone: "beige",
    
  },

  {
    img: "https://i.pinimg.com/originals/2d/f1/4f/2df14f42fa4789d63326beb94fc28ab7.jpg",
    title: "Denim Cowboy jacket",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Puma",
    color: "oldmoney",
    category: "inverted traingle",
    merch: "taylorswift",
    skintone: "beige",
    
  },
  {
    img: "https://i.pinimg.com/originals/7f/bd/fe/7fbdfed6a8c12b87947986426ec1a97c.jpg",
    title: "Arabian style jacket",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Puma",
    color: "oldmoney",
    category: "rectangle",
    merch: "taylorswift",
    skintone: "beige",
    
  },
  {
    img: "https://i.pinimg.com/originals/33/17/9b/33179b466bc6ea3b812dc688a2ba85b3.jpg",
    title: "Unisex-Adult jacket",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Puma",
    color: "oldmoney",
    category: "rectangle",
    merch: "taylorswift",
    skintone: "beige",
   
  },
  {
    img: "https://i.pinimg.com/originals/ef/92/1e/ef921e7c705024abb976ac9f960f6214.png",
    title: "Roma Basic jacket",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Puma",
    color: "y2k",
    category: "rectangle",
    merch: "taylorswift",
    skintone: "beige",
    
  },
  {
    img: "https://i.pinimg.com/originals/18/3e/e9/183ee9bdf17ac3d25c3d930576037d00.jpg",
    title: "Pacer blue jacket",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Puma",
    color: "y2k",
    category: "inverted - traingle",
    merch: "taylorswift",
    skintone: "beige",
    
  },

  {
    img: "https://i.pinimg.com/originals/f5/3b/cc/f53bccb2a160a25e7d515a37b1ddfd3c.jpg",
    title: "Purple curl dress",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    company: "Only",
    color: "y2k",
    category: "hourglass",
    merch: "taylorswift",
    skintone: "olive",
    
  },
  {
    img: "https://i.pinimg.com/originals/b1/87/21/b18721f0a7e6c45e2d823aeee7a9b7ca.jpg",
    title: "Black dress with sleeves",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    company: "Only",
    color: "y2k",
    category: "hourglass",
    merch: "kpop",
    skintone: "olive",
  },
  {
    img: "https://i.pinimg.com/originals/a9/27/80/a92780cd126a7031448da465ccbff985.jpg",
    title: "Pink dress",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    company: "Only",
    color: "y2k",
    category: "hourglass",
    merch: "kpop",
    skintone: "olive",
  },
  {
    img: "https://i.pinimg.com/originals/6b/85/43/6b8543ffa3fd96f3e631b1faf6922f7c.jpg",
    title: "White dress",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    company: "Only",
    color: "retro",
    category: "hourglass",
    merch: "kpop",
    skintone: "olive",
  },
  {
    img: "https://i.pinimg.com/originals/04/fd/92/04fd923d5a95d2e939c3fbeebd2db29c.jpg",
    title: "Bodycon short dress",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Only",
    color: "retro",
    category: "hourglass",
    merch: "kpop",
    skintone: "tanned",
  },
  {
    img: "https://i.pinimg.com/originals/4c/bb/cd/4cbbcda898c682f1c507288256b60d61.jpg",
    title: "Butterfly crop top",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Tokyo Talkies",
    color: "retro",
    category: "hourglass",
    merch: "kpop",
    skintone: "tanned",
  },
  {
    img: "https://i.pinimg.com/originals/2a/70/1b/2a701bc91df13fdb1b89505cdc3dae92.jpg",
    title: "Conquttee style crop top",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    company: "Only",
    color: "retro",
    category: "hourglass",
    merch: "kpop",
    skintone: "tanned",
  },
  {
    img: "https://i.pinimg.com/originals/c1/ab/3c/c1ab3c481c1dfbeb812ed99807a494e3.jpg",
    title: "Star styled jean",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Tokyo Talkies",
    color: "retro",
    category: "hourglass",
    merch: "kpop",
    skintone: "tanned",
  },
  {
    img: "https://i.pinimg.com/originals/21/1f/e7/211fe7be94c51ca8f52356178653478d.png",
    title: "Spidey shorts",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Tokyo Talkies",
    color: "retro",
    category: "oval",
    merch: "kpop",
    skintone: "tanned",
  },

  {
    img: "https://i.pinimg.com/originals/77/bd/d6/77bdd63ecb46776277158f710c602aa7.jpg",
    title: "Y2k styles tshirt",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Levis",
    color: "darkacademia",
    category: "oval",
    merch: "kpop",
    skintone: "tanned",
  },
  {
    img: "https://i.pinimg.com/originals/91/83/d1/9183d181966e2ad29f304fae5539481b.jpg",
    title: "Nirvana tshirt",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Adidas",
    color: "darkacademia",
    category: "oval",
    merch: "spiderman",
    skintone: "olive",
  },
  {
    img: "https://i.pinimg.com/originals/bb/a3/e6/bba3e6c526f96c191668866554768d6e.jpg",
    title: "Jennis aura tshirt",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Adidas",
    color: "darkacademia",
    category: "oval",
    merch: "spiderman",
    skintone: "dark",
    
  },
  {
    img: "https://i.pinimg.com/originals/3c/52/26/3c52265a909623667b7d1d917f05cfa5.jpg",
    title: "Anime black tshirt",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Levis",
    color: "darkacademia",
    category: "oval",
    merch: "spiderman",
    skintone: "dark",
    
  },
  {
    img: "https://i.pinimg.com/originals/0c/34/33/0c34334dc364a807dde3a4e91cd400d6.jpg",
    title: "Spidey blue tshirt",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Adidas",
    color: "darkacademia",
    category: "oval",
    merch: "spiderman",
    skintone: "dark",
    
  },
];
export default data;
